### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Gustemps** [mehmetgoren/feniks#2]
I can reach the login page, but no success on login... some of the errors in the console are:

Any help?

webapp-instance             | 2023/01/30 16:28:58 [error] 33#33: *168 "/usr/share/nginx/html/socket.io/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1", host: "localhost:8080"

detect_service_pytorch-instance | WARNING:logger:new type (ServiceModel) added to RedisMapper cache
detect_service_pytorch-instance | Redis host: 127.0.0.1
detect_service_pytorch-instance | Redis port: 6379
detect_service_pytorch-instance | Traceback (most recent call last):
detect_service_pytorch-instance |   File "main_pytorch.py", line 26, in <module>
detect_service_pytorch-instance |     main()
detect_service_pytorch-instance |   File "main_pytorch.py", line 17, in main
detect_service_pytorch-instance |     detector = create_object_detector_model()
detect_service_pytorch-instance |   File "main_pytorch.py", line 11, in create_object_detector_model
detect_service_pytorch-instance |     model = load_model()
detect_service_pytorch-instance |   File "/app/core/pytorch/model_loader.py", line 10, in load_model
detect_service_pytorch-instance |     model = torch.hub.load(config.torch.model_name, config.torch.model_name_specific,
detect_service_pytorch-instance |   File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 402, in load
detect_service_pytorch-instance |     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
detect_service_pytorch-instance |   File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 170, in _get_cache_or_reload
detect_service_pytorch-instance |     repo_owner, repo_name, branch = _parse_repo_info(github)
detect_service_pytorch-instance |   File "/opt/conda/lib/python3.8/site-packages/torch/hub.py", line 117, in _parse_repo_info
detect_service_pytorch-instance |     repo_owner, repo_name = repo_info.split('/')
detect_service_pytorch-instance | ValueError: not enough values to unpack (expected 2, got 1)

**Comment by mehmetgoren** [comment]
You may have trouble because of the lack of configuration settings. Could you also share both mngr-instance and ffmpeg_service-instance logs? You can get them easily by using the Visual Sudio Code Docker Extension.

**Comment by Gustemps** [comment]
I use Linux command line so no visual studio, maybe log files somewhere?

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mehmetgoren** [comment]
Ok, you can get them via those commands:
docker logs mngr-instance
docker logs ffmpeg_service-instance

**Comment by mehmetgoren** [comment]
Sorry but I couldn't see any logs from your previous message. Could you please send them again.

There is no packages requirement. You just need a Docker & Docker Compose installed Linux machine, nothing more.

**Comment by mehmetgoren** [comment]
No chance, Could you send them by using Github itself instead of Outlook ?

**Comment by Gustemps** [comment]
[ffmpg.log](https://github.com/mehmetgoren/feniks/files/10537679/ffmpg.log)
[mngr.log](https://github.com/mehmetgoren/feniks/files/10537680/mngr.log)
Here they are!

**Comment by mehmetgoren** [comment]
The web server failed to start due to it couldn't connect to Redis. Are you sure Redis was already installed? (you can check it by the 'docker stats' command).

If Redis is running just fine on your machine, there must be a communication problem among the containers which leads us to a network issue since the containers are running at network-host mode.

Firstly, I think you should make a fresh Ubuntu installation as you said. I can help you over Discord if the issue still persist.

**Comment by Gustemps** [comment]
Still not able to login
Installed mongodb as a service an it runs.
Installed redis as a service an it runs.
tryed with pytorch FAILS
tryed with tf FAILS

Do i need to register a new account first or the login credentials i asume L:"admin" P:"admin" are correct?

thanks in advice.

**Comment by mehmetgoren** [comment]
Could you share your docker-compose.yml file. In this way, I can run it in my virtual environment and see what is the problem.

**Comment by Gustemps** [comment]
Here it is! 

How i can find you in discord? i'm a newbie in this.

**Comment by mehmetgoren** [comment]
Here is the Discord channel invite link: https://discord.gg/rHvkS3NA
